blank_issues_enabled: false
contact_links:
  - name: Ask a question on Slack
    url: https://join.slack.com/t/nunchistudio/shared_invite/zt-uxsr7ff7-KpmDn7QJMGIPUUZj7HNKZg
    about: Ask questions and discuss with other community members
